import type { Metadata } from "next";
import "./globals.css";
import "./tailwind.css";
import { ReactNode } from "react";
import localFont from "next/font/local";
import { CookiesProvider } from "next-client-cookies/server";
import ProgressProvider from "@/components/providers/ProgressProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import Header from "@/components/common/header";
import Sidebar from "@/components/common/sidebar";

export const metadata: Metadata = {
    title: "LET",
    description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
    src: "../assets/fonts/pretendard.woff2",
    variable: "--font-prendard",
    weight: "100 900",
});

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>) => {
    return (
        <html lang="ko">
            <body className={pretendard.variable}>
                <ProgressProvider>
                    <QueryProvider>
                        <CookiesProvider>
                            <div className="w-full min-h-screen bg-bg">
                                <Header />
                                <div className="w-full flex justify-center gap-5 pt-5">
                                    <Sidebar />
                                    {children}
                                </div>
                            </div>
                        </CookiesProvider>
                    </QueryProvider>
                </ProgressProvider>
            </body>
        </html>
    );
};

export default RootLayout;
