import type { Metadata } from "next";
import "./globals.css";
import "./tailwind.css";
import { ReactNode } from "react";
import { pretendard } from "@/styles/fonts";
import { CookiesProvider } from "next-client-cookies/server";
import QueryProvider from "@/components/providers/QueryProvider";
import LoadingProvider from "@/components/providers/LoadingProvider";

export const metadata: Metadata = {
    title: "LET",
    description: "Generated by cher1sh-next-app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>) => {
    return (
        <html lang="ko">
            <body className={pretendard.variable}>
                  <QueryProvider>
                      <CookiesProvider>
                          <LoadingProvider />
                          <div className="w-full min-h-screen bg-bg">
                              {children}
                          </div>
                      </CookiesProvider>
                  </QueryProvider>
            </body>
        </html>
    );
};

export default RootLayout;
